#!/bin/sh
set -e

NAME=`basename $0`
URL="http://aspell.net"

DATA=$(curl -Ss "https://repology.org/badge/latest-versions/$NAME.svg")
VERSION=${DATA%</text>*}
VERSION=${VERSION##*>}

cat <<EOF
<?xml version="1.0" ?>

<rdf:RDF
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns="http://purl.org/rss/1.0/">

<channel rdf:about="http://pwhois.org">
<title> $NAME </title>
<link></link>
<description> $NAME </description>
</channel>

<item rdf:about="1">
<title> $NAME v$VERSION </title>
<link> $URL </link>
<description>
</description>
</item>
EOF

# End of file
